[
    {
        "isTemplate": false,
        "completed": false,
        "id": "97461a85-4344-4337-bb1c-b0c19dd88135",
        "organizationId": "66dc1dae-f8e5-4089-9fb8-9a37682a9351",
        "title": "This is a test",
        "createdBy": "cbfaf1fd-3ddf-4a7b-89dd-96f1ef049591",
        "createdAt": 1596063166000,
        "repeats": false,
        "isPublic": false,
        "completionMode": "first"
    }
]